# Generated by Django 5.2 on 2025-04-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('ph', models.FloatField()),
                ('moisture', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CropPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_address', models.CharField(max_length=100)),
                ('crop', models.CharField(max_length=50)),
                ('cid', models.TextField(blank=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('ph', models.FloatField()),
                ('moisture', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('N', models.IntegerField()),
                ('P', models.IntegerField()),
                ('K', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
