# Generated by Django 5.2 on 2025-04-12 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CropPrediction',
        ),
    ]
